version: '3.8'
services:
    #Micro servicio dados
    dados:    
        build: ./microservicio-dados/
        container_name: dadosserver
        ports:
            - "8081:8080"    
    #Micro servicio torneo-------------
    torneo:    
        build: ./microservicio-torneo/torneo
        container_name: torneoserver
        ports:
            - "8080:8080"
    dbtorneo:
        image: mysql:latest        
        restart: always        
        command: --default-authentication-plugin=mysql_native_password        
        container_name: dbserver-torneo
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: torneo_sa    
        #ports:
        #    - "3306:3306"           
        volumes:
            - "./microservicio-torneo/database/setup.sql:/docker-entrypoint-initdb.d/1.sql"
            - ./microservicio-torneo/database/mysql/data:/var/lib/mysql
    #Micro servicio tokens--------------------
    tokens:
        build: ./microservicio-tokens/tokens
        container_name: tokensserver
        ports:
            - "8082:8080"
    dbtokens:  
        image: mysql:latest        
        restart: always        
        command: --default-authentication-plugin=mysql_native_password        
        container_name: dbserver-tokens
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: tokens_sa    
        #ports:
        #    - "3306:3306"           
        volumes:
            - "./microservicio-tokens/database/setup.sql:/docker-entrypoint-initdb.d/1.sql"
            - ./microservicio-tokens/database/mysql/data:/var/lib/mysql          